AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Max: 50

Naming/MethodParameterName:
  Enabled: false

Metrics/LineLength:
  Max: 150
