AllCops:
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Exclude:
    - 'spec/**/*'

Naming/MethodParameterName:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

